import { NavBar } from "@/components";
import Head from "next/head";
import Footer from "./Footer";

export default function Layout(props: { children: React.ReactNode }) {
  return (
    <>
      <Head>
        <title>Mini Trade</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <NavBar />
      <main>{props.children}</main>
      <Footer />
    </>
  );
}
